### ISSUE TITLE
Django Back-end Protocol 4

### ISSUE THREAD

**Issue by ai** [logux/logux#33]
Next Logux Server will use new [Back-end Protocol](https://github.com/logux/docs/tree/next/protocols/backend):

- [ ] Now we are using objects for commands and answers instead of arrays.
- [ ] auth` command has 2 additional keys: `cookie: { name: "value", … }` with HTTP cookie and `headers: { name: value }` (it is *not* HTTP headers, it is special user metadata like language).
- [ ] `action` command has extra `headers` key.
- [ ] The version was bumped to `4`.
- [ ] Add API to get `cookie` and `headers` data in auth callback.
- [ ] Add API to get `headers` during the action processing.
- [ ] Allow to return actions from the `load` method.
- [ ] Back-end check client’s `subprotocol` in `auth` command
- [ ] Back-end set server’s `subporotocol` in `authenticated` answer
- [ ] On subscription send back actions from `load` by `action` answer in HTTP response

To get Logux Server with the latest back-end protocol:

```sh
yarn remove @logux/server
yarn add @logux/server@logux/server#next
```

**Comment by egregors** [comment]
@ai few questions about Auth Command: 
* `token?: str` is optional?
* should the app crush if Auth Command does not contain `authId` or `userId` keys?

**Comment by ai** [comment]
> why token?: str is optional?

Because developers may use cookie-only auth (it is even preferred way, to protect token from XSS).

> (as key in auth cmd or as key in cookie dict)?

Developer can put a token in a cookie with any name. For instance, `cookie.AuthPassword`.

> should the app crush if Auth Command does not contain authId or userId keys?

Yeap

> Probably details would be less confusing kay name. IMHO.

Good idea. I updated spec https://github.com/logux/docs/commit/4a3acc083be7f5e3abfb24c8fa15ea0083757826

**Comment by egregors** [comment]
> Developer can put a token in a cookie with any name. For instance, cookie.AuthPassword.

The `logux_auth: Callable[[str, str], bool])` function expect `user_id` and `token`. How should I get `token` from cookie if the key name is unknown? 

I suppose  I can add one more user settings, like: `COOKIE_AUTH_TOKEN_KEY`. So the user would provide which key I should try to find in the cookies. 

Yep, I guess it will be fine. Isn't it, @ai?

**Comment by ai** [comment]
> The logux_auth: Callable[[str, str], bool]) function expect user_id and token. 

It JS I moved signature from a list `string, string`to a map `{ userId, token, cookie, headers }`. Should we do the same here?

**Comment by egregors** [comment]
> > The logux_auth: Callable[[str, str], bool]) function expect user_id and token.
> 
> It JS I moved signature from a list `string, string`to a map `{ userId, token, cookie, headers }`. Should we do the same here?

I guess so.

**Comment by ai** [comment]
> logux_auth: Callable[[str, Optional[str], Dict, Dict], bool]):

Why not `logux_auth: Callable[[Dict], bool]):`? And in the `Dict` you will have `user_id`, `token`, `cookie` and `headers` keys?

**Comment by egregors** [comment]
> Why not logux_auth: Callable[[Dict], bool]):? And in the Dict you will have user_id, token, cookie and headers keys?

Because this is abstraction leak. And this is non idiomatic for python. Extracting and validation  values from some featureless dict are not responsibility of auth function. That way we may just pass full Action object for consumer, and got just ActionCommand at all. 

I believe auth func even with 4 args better then passing dictionary. 

By this way consumer will get fully described interface with the understanding of args types, what args might be optional, what kind of defaults them have.

**Comment by ai** [comment]
> I believe auth func even with 4 args better then passing dictionary.

If Django developers will like it I don’t mind.

It could be a JS specific pattern to use objects as an argument.

**Comment by egregors** [comment]
My progress:

* [x]  Now we are using objects for commands and answers instead of arrays.
* [x]  auth`command has 2 additional keys:`cookie: { name: "value", … }`with HTTP cookie and`headers: { name: value }` (it is _not_ HTTP headers, it is special user metadata like language).
* [x]  `action` command has extra `headers` key.
* [x]  The version was bumped to `4`.
* [x]  Add API to get `cookie` and `headers` data in auth callback.
* [x]  Add API to get `headers` during the action processing.
* [x]  Allow to return actions from the `load` method.
* [ ]  Back-end check client’s `subprotocol` in `auth` command
* [ ]  Back-end set server’s `subporotocol` in `authenticated` answer
* [x]  On subscription send back actions from `load` by `action` answer in HTTP response

**Comment by egregors** [comment]
@ai The last question is what the expected behavior for subprotocols processing? 
So, I added the SUBPROTOCOL settings key for a server. It will be a list of the strings, with a sequence of supported versions like:
```python
# settings.py
LOGUX_CONFIG = {
    [...]
    'SUBPROTOCOL': [
        '1.0.0',
        '1.0.1',
    ]
}
```

What should I do if AUTH command from Logux proxy has a subprotocol version which does not support by the server? 

And, about 
> Back-end set server’s subprotocol in authenticated answer

I guess I should use here the biggest one from the `settings.LOGUX_CONFIG['SUBPROTOCOL']`, isn't it? 

Or I got it wrong and `settings.LOGUX_CONFIG['SUBPROTOCOL']` should be just a string, and I need to check compatibility by semver arithmetic?

**Comment by egregors** [comment]
@ai 

I added `semanticversion` to the project and we can parse NPM-based ranges for subprotocols! 

Just to be sure I got all correctly:
* ALL `AUTH` commands contain `subprotocol` in the action body
* `ACTION` commands COULD contain  `subprotocol` key but in the `meta` body, not in `action` body like `AUTH`
* If subprotocol version of client does not match server-support range, the server should return `wrongSubprotocol` answer

**Comment by ai** [comment]
> ALL AUTH commands contain subprotocol in the action body

Yeap

> ACTION commands COULD contain subprotocol key but in the meta body, not in action body like AUTH

Yeap

> If subprotocol version of client does not match server-support range, the server should return wrongSubprotocol answer

Yeap

**Comment by egregors** [comment]
@ai [2.0.0rc1](https://pypi.org/project/logux-django/2.0.0rc1/) is ready. 

Before release should be implemented: 

- [ ] brute-force protection
- [ ] pass 19 and 20 step for backend-test
- [ ] add backend-test to CI pipeline
- [ ] update doc's in the repo
- [ ] update doc's on Logux site
- [ ] release new non RC version in PyPI
