### ISSUE TITLE
Reorganize client API

### ISSUE THREAD

**Issue by ai** [logux/logux#64]
- [x] Add `Client API` section with Logux State API
- [x] Move `Redux API` and `Vuex API` inside `Client API`

**Comment by erictheswift** [comment]
Related to documentation changes:

it make sense to sync repository README headers from https://github.com/logux/logux/blob/main/README.md (correct one)

because some are kinda outdated:
https://github.com/logux/server/blob/main/README.md — broken Roadmap link
https://github.com/logux/examples — dead empty repo

**Comment by ai** [comment]
I fixed links in `next` branch by mistake. Let’s wait for `next` merging into `main`.

I will create examples when I will finish Logux State.
